import type { Metadata } from "next";
import "@/styles/common.scss";
import Gnb from "@/components/common/Gnb";
import Fnb from "@/components/common/Fnb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Gnb />
        {children}
        <Fnb />
      </body>
    </html>
  );
}
